### ISSUE TITLE
Support for default duplicator blacklist

### ISSUE THREAD

**Issue by Bubbus** [wiremod/advduplicator#64]
Garry's default duplicator supports entity blacklisting via `duplicator.IsAllowed(classname)` and `Entity.DoNotDuplicate` - I'd love Adv. Duplicator to adhere to these as it'd be useful to blacklist specific entities in an installation-independent manner.  Can take a look at this if you're open to pull requests.

Related discussion: http://facepunch.com/showthread.php?t=1442021

**Comment by Grocel** [comment]
As it is fixed now, it can be closed. :)
