### ISSUE TITLE
Admin settings 

### ISSUE THREAD

**Issue by TheMerkyShadow** [wiremod/advduplicator#68]
So my friend has a server and the admins are able to dupe other admin's e2s and contraptions and we have tried to make it so they cannot but we have been unsuccessful in both advanced duplicator 1+2.
Can someone shed the light on this issue so we could fix it?
Would be very appreciated, thanks

**Comment by TomyLobo** [comment]
They are the admins, they can do whatever the heck they want. if you don't trust the admins, don't play there.
You can make them something below admin, yet elevated enough to do whatever they're there to do

**Comment by Divran** [comment]
It's the job of your admin mod OR your prop protection mod to do this, not adv duplicators. Go check your admin mod or prop protection mod settings.
