### ISSUE TITLE
Timed Paste Broken after the new Gmod update

### ISSUE THREAD

**Issue by neithque** [wiremod/advduplicator#71]
If dupe is spawned with timed paste, it will spawn unfrozen no matter the settings.

**Comment by TomyLobo** [comment]
So it works again?

**Comment by TomyLobo** [comment]
@neithque so it works again?

**Comment by neithque** [comment]
On some servers seems it works fine. On mine it didn't. I removed freeze check, so props are frozen no matter what. That fixed it. Seems to make less lag too, that old freeze had ent spike whenever you paste something.
