### ISSUE TITLE
Props unfreeze on paste

### ISSUE THREAD

**Issue by fruitwasp** [wiremod/advduplicator#72]
### Steps to reproduce
1. Check the Paste Frozen checkbox in the config panel (optional)
2. Paste this dupe: http://pastebin.com/Gtq6vVzx
3. Wait for all entities to spawn and see them unfreeze

### Expected behavior
All pasted entities are frozen

### Actual behavior
All pasted entities are unfrozen

### Error(s)
none.

**Comment by Nebual** [comment]
Can confirm, seems to happen with any dupe that triggers the 'slow paste' threshold.

Upon experimentation, it seems E:SetParent() now unfreezes the prop, albeit the physics stay asleep. Should be a simple case of refreezing it.

**Comment by Nebual** [comment]
We should update Workshop soon, once others confirm this works.

**Comment by TomyLobo** [comment]
Garry! :fist:

**Comment by bigdogmat** [comment]
Well it was Willox but it improved a lot of the process if I remember what he said

**Comment by fruitwasp** [comment]
It's fixed

**Comment by viktorkovarik** [comment]
Please update workshop version.
