### ISSUE TITLE
Duplicator doesn't save materials

### ISSUE THREAD

**Issue by timthefunnyman** [wiremod/advduplicator#73]
When duplicating props that are materialized, the materials aren't saved/pasted with the props. I don't see any errors in console when pasting.

Props that are colored using the color tool seem to be saved, though.

**Comment by Divran** [comment]
It only saves materials that were applied using a tool or script that calls the correct "save material" function. iirc E2 doesn't do this

**Comment by timthefunnyman** [comment]
Right, I'm talking about props that are materialized using the material tool.

**Comment by TomyLobo** [comment]
and you're talking about Garry's Duplicator, Advanced Duplicator or Advanced Duplicator 2?

**Comment by timthefunnyman** [comment]
Advanced Duplicator. It's happening on my DarkRP server: 192.95.60.28:27015.

**Comment by TomyLobo** [comment]
Are all of your mods up-to-date?
Does using the GitHub version change anything?
Did you try turning it off and on? :)

**Comment by Anticept** [comment]
Doing an issue cleanup. If they come back and answer your question, they can reopen this.
