### ISSUE TITLE
Adv Dupe 2 won't area-copy or save map

### ISSUE THREAD

**Issue by EdoTM** [wiremod/advduplicator#78]
Hello everyone, I have installed **Advanced Duplicator 2** recently. The single duplication works fine, even if the props are connected together, but when I try either to area-copy or save a map I get this error in the console:
```

[Advanced Duplicator 2] lua/advdupe2/sv_clipboard.lua:163: bad argument #1 to 'pairs' (table expected, got no value)
  1. pairs - [C]:-1
   2. CopyEntTable - lua/advdupe2/sv_clipboard.lua:163
    3. AreaCopy - lua/advdupe2/sv_clipboard.lua:360
     4. RightClick - lua/weapons/gmod_tool/stools/advdupe2.lua:210
      5. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:250

```
Please help me! How can I fix this? Am I the only one with this problem? Thanks in advance.

**Comment by thegrb93** [comment]
Already fixed most likely
