### ISSUE TITLE
ADVDupe-Error:Failed to make!

### ISSUE THREAD

**Issue by LolKasr** [wiremod/advduplicator#79]
Hello, i downloaded 1 dupe and when in placing it down it says: advdupe-error: failed to make "gmod_wire_user" or something else like: advdupe-error: failed to make "gmod_wire_ranger" and others like this, But in singleplayer everything works fine with that same addon!! so guys please help me :) Is there problem with my server? and how do i fix it?

**Comment by Divran** [comment]
Looks like your server doesn't have wiremod installed.
