### ISSUE TITLE
When i try use adv dupe 2 it makes this error

### ISSUE THREAD

**Issue by Speedyriley** [wiremod/advduplicator#83]
[Advanced Duplicator 2] lua/advdupe2/sv_file.lua:118: attempt to index field 'AdvDupe2' (a nil value)
  1. func - lua/advdupe2/sv_file.lua:118
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by TomyLobo** [comment]
any other addons?

**Comment by thegrb93** [comment]
Yeah its the same thing Divran mentioned. AdvDupe2 getting removed from the ply table. I'll put a reassignment in there too.

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/pull/263/files

**Comment by TomyLobo** [comment]
wait what, why is that even in there and not in a local,
 cleaned up with each player disconnect

**Comment by thegrb93** [comment]
Because its easier that way

**Comment by thegrb93** [comment]
Feel free to refactor it if you like.
