### ISSUE TITLE
AdvDup2 doesn't copy npc_mannable_turret.

### ISSUE THREAD

**Issue by JustReg2Download** [wiremod/advduplicator#87]
Even if  npc_mannable_turret is green in area copy tool, it still doesn't appear at copied building.
Later I got new issue.
Issue 1
![20201211154801_1](https://user-images.githubusercontent.com/72761693/101911069-896c3480-3bc8-11eb-8275-693a3b5d9645.jpg)
![20201211154912_1](https://user-images.githubusercontent.com/72761693/101911084-8e30e880-3bc8-11eb-892f-a0ef161f5075.jpg)

Issue 2
"DUPLICATOR: ERROR, NoCollide Constraint could not find an entity!"

![20201211154001_1](https://user-images.githubusercontent.com/72761693/101910564-c5eb6080-3bc7-11eb-971b-4bf7470e5f79.jpg)

**Comment by thegrb93** [comment]
Probably just need duplicator.Allow("npc_mannable_turret") for it to work

**Comment by thegrb93** [comment]
Whatever addon you're using to spawn those should incorporate duplicator support. I don't think those should be spawnable via duplicator without the addon installed.
